### ISSUE TITLE
Your resouces dont have files ( throw file not found )

### ISSUE THREAD

**Issue by ishrek** [esentis/Flutter-Movies-Application#30]
Hi, 

i pulled your code but have problems
- Your resource expired.  Please, could you tell about for create resouces like you.
- No .env file or what else.  I can not find .env in your source code. please tell me where is it 

thank you

**Comment by esentis** [comment]
Hello friend,

I guess by resource expiring you mean the movies are not shown right ? That's because all info comes from the TMDB API.  If you check on connection.dart where the connection is made, I pass the API Key with DotEnv package, which basically holds sensitive data like API keys. The .env file is on .gitignore obviously, that's why you can't really connect to TMDB with my Key and you cant find the file in the source code. 

The easiest workaround here is just to go to TMDB, make a new API key and pass the key where is needed at connection.dart and the app will most probably work as intended :)
